#%RAML 0.8
title: REST API Human Resource List
baseUri: http://mule.aimtec.cz/hrl/api

schemas:
  - employee: !include schemas/employee.schema.json

/employee:
  description: Emploee
  post:
    description: Create new employee
    body: 
      application/json: 
        schema: employee
        example: !include examples/employee.post.json
    responses: 
      200:
        body: 
          application/json: 
              schema: employee
              example: !include examples/employee.json    
  /{id}:
    get: 
      description: Get details
      responses: 
        200: 
          body: 
            application/json: 
              schema: employee
              example: !include examples/employee.json    